- name: creates directory for holding manifests
  file:
    path: ~/openconnect
    state: directory

- name: copy required files
  copy:
    src: files/docker-compose.yml
    dest: ~/openconnect/docker-compose.yml

# use files parameter to use multiple docker-compose.yml files
- name: deploy Docker Compose stack
  docker_compose:
    project_src: ~/openconnect
    files:
    - docker-compose.yml
