version: '3.8'
services:
  openconnect:
    image: quay.io/aminvakil/ocserv:latest
    container_name: openconnect
    restart: always
    privileged: true
    ports:
      - 4443:443
      - 4443:443/udp
    environment:
      - CA_CN=example.com
      - CA_ORG=example.com
      - CA_DAYS=365
      - SRV_CN=example.com
      - SRV_ORG=example
      - SRV_DAYS=365
      - NO_TEST_USER=1
